[project]
name = "vidjil"
version = "1.0.1-dev1"
description = "Wrapper around tool to detect reads with CDR3 in FASTQ files"
authors = [{name = "nikita.syzrantsev@gmail.com"}]
requires-python = ">=3.10"